/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f4xx.h>



 uint8_t INTERRUPT_TRIGGERED = 0;
int main(void)
{
//configure user button (interrupt trigger)
	GPIO_Handle_t userButton = {0};
	userButton.pGPIOx = GPIOA;
	userButton.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IT_RT;
	userButton.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_0;
	GPIO_PeriClockControl(userButton.pGPIOx, ENABLE);
	GPIO_IRQInterruptConfig(IRQ_NO_EXTI0, ENABLE);
	GPIO_Init(&userButton);

//configure red led
	GPIO_Handle_t redLed = {0};
	redLed.pGPIOx = GPIOD;
	redLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUPUT;
	redLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_14;
	GPIO_PeriClockControl(redLed.pGPIOx, ENABLE);
	GPIO_Init(&redLed);


	while(1){
		if(INTERRUPT_TRIGGERED){
			GPIO_WriteToOutputPin(redLed.pGPIOx, redLed.GPIO_PinConfig.GPIO_PinNumber, ENABLE);
		}else{
			GPIO_WriteToOutputPin(redLed.pGPIOx, redLed.GPIO_PinConfig.GPIO_PinNumber, DISABLE);
		}

	}
}

void EXTI0_IRQHandler(){
	GPIO_IRQHandler(GPIO_PIN_0);
	INTERRUPT_TRIGGERED++;


}


